import random
num = random.randint(1, 60)
print(num)
num = random.randint(1, 60)
print(num)
num = random.randint(1, 60)
print(num)
num = random.randint(1, 60)
print(num)
num = random.randint(1, 60)
print(num)
num = random.randint(1, 60)
print(num)
